### PR TITLE
build-release: get external_deps version from build.sh

### PR DESCRIPTION
**Pull request by illwieckz**
See https://github.com/DaemonEngine/Daemon/pull/638

### CODE REVIEW

**Review by necessarily-equal — COMMENTED** [review]
I don't know the setup enough to say if it's a good idea. Otherwise LGTM

**Comment by illwieckz** [comment]
The list of deps to be built also had to be updated in the Dockerfile. Too bad no one ever implemented a virtual package name for `build.sh` for the current supported deps to build, otherwise we would just use that virtual package name in such Dockerfile without having to maintain lists at multiple places. Sarcasm aside, this is part of why I'm in favor of turning `build.sh` into a full featured program with internal data consistency checks and helpers to print things even if it doubles the size of the source code.

**Comment by slipher** [comment]
See #18

**Comment by slipher** [comment]
>  Too bad no one ever implemented a virtual package name for build.sh for the current supported deps to build, otherwise we would just use that virtual package name in such Dockerfile without having to maintain lists at multiple places.

Under no circumstances do we build the entire set of supported deps in the release scripts. For Windows and Mac we just use the prebuilt ones, with the exception of rebuilding a faulty GMP (which I'm removing in #18). For Linux we build a random subset of the optional deps for which the package manager does not provide satisfactory static libs.

**Comment by illwieckz** [comment]
It doesn't mean this kind of list cannot be stored where the actual list of supported packages exist, to reduce the amount of scripts to edit and prevent any discrepancies. For the sake of not assuming our needs we have to duplicate the information in multiple places.

**Comment by illwieckz** [comment]
I merged the `Dockerfile` change separately.

**Pull request closed without merging**
